### ISSUE TITLE
Setup lib-colladamodel

### ISSUE THREAD

**Issue by SirJackblue** [hea3ven/lib-colladamodel#3]
Hello !

Since 2 days, I try to deploy workspace with your collada lib and your mod, PandoriaChest.
But in Creative Inventory, when I approached them in Decoration Blocks Tab my client crash like this crash report : http://pastebin.com/55K59hNc 

Your help will be really appreciate :D 

Have a nice day !
Cordially, Jackblue

**Comment by hea3ven** [comment]
Don't use this library, it's old and bad. Sorry to have wasted your time.

About the error, are you using the release, or the latest commit?, that's probably the issue.
